apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: consul-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.consul.resources.storage }}"
