apiVersion: v1
kind: Service
metadata:
  name: minio-external
spec:
  type: {{ .Values.minio.serviceType }}
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      {{- if contains "NodePort" .Values.minio.serviceType }}
      nodePort: {{ .Values.minio.nodePort }}
      {{- end }}
  selector:
    app: minio
